spring.application.name=randomly-backend

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.com.yourapp.websocket=DEBUG

server.address=0.0.0.0
server.port=${PORT:8080}
